export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

export const GET_STARTUP_REQUEST = 'GET_STARTUP_REQUEST';
export const GET_STARTUP_SUCCESS = 'GET_STARTUP_SUCCESS';
export const GET_STARTUP_FAILURE = 'GET_STARTUP_FAILURE';

export const SET_INACTIVE_TIMESTAMP = 'SET_INACTIVE_TIMESTAMP';

export const LOGIN_MOBILE_REQUEST = 'LOGIN_MOBILE_REQUEST';
export const LOGIN_MOBILE_SUCCESS = 'LOGIN_MOBILE_SUCCESS';
export const LOGIN_MOBILE_FAILURE = 'LOGIN_MOBILE_FAILURE';

export const GET_PROFILE_DATA_REQUEST='GET_PROFILE_DATA_REQUEST';
export const GET_PROFILE_DATA_SUCCESS='GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILURE='GET_PROFILE_DATA_FAILURE';

export const UPDATE_PROFILE_DATA_REQUEST='UPDATE_PROFILE_DATA_REQUEST';
export const UPDATE_PROFILE_DATA_SUCCESS='UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_FAILURE='UPDATE_PROFILE_DATA_FAILURE';
export const UPDATE_PROFILE_IMAGE_REQUEST='UPDATE_PROFILE_IMAGE_REQUEST';
export const UPDATE_PROFILE_IMAGE_SUCCESS='UPDATE_PROFILE_IMAGE_SUCCESS';
export const UPDATE_PROFILE_IMAGE_FAILURE='UPDATE_PROFILE_IMAGE_FAILURE';

export const REFRESH_TOKEN_REQUEST='REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS='REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE='REFRESH_TOKEN_FAILURE';

export const UPLOAD_SHOP_IMAGE_REQUEST='UPLOAD_SHOP_IMAGE_REQUEST';
export const UPLOAD_SHOP_IMAGE_SUCCESS='UPLOAD_SHOP_IMAGE_SUCCESS';
export const UPLOAD_SHOP_IMAGE_FAILURE='UPLOAD_SHOP_IMAGE_FAILURE';

export const UPLOAD_SHOP_DETAILS_REQUEST='UPLOAD_SHOP_DETAILS_REQUEST';
export const UPLOAD_SHOP_DETAILS_SUCCESS='UPLOAD_SHOP_DETAILS_SUCCESS';
export const UPLOAD_SHOP_DETAILS_FAILURE='UPLOAD_SHOP_DETAILS_FAILURE';

export const GET_SHOP_DETAILS_REQUEST='GET_SHOP_DETAILS_REQUEST';
export const GET_SHOP_DETAILS_SUCCESS='GET_SHOP_DETAILS_SUCCESS';
export const GET_SHOP_DETAILS_FAILURE='GET_SHOP_DETAILS_FAILURE';